# Generated by Django 5.1.3 on 2024-12-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepayment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
