# Generated by Django 5.1.3 on 2024-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_alter_coursepayment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepayment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
