# Generated by Django 5.1.3 on 2024-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_alter_coursepayment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена в рублях"),
        ),
        migrations.AlterField(
            model_name="coursepayment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
